version: '3'
services:
  db:
    image: postgres:11.6-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/date_suggester
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      S3_BUCKET_NAME: test_bucket
    tty: true
    stdin_open: true
volumes:
  db: