version: '3'
services:
  db:
    image: postgres:11.6-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:cached
    environment:
      TZ: Asia/Tokyo
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/date_suggester:cached
      - bundle:/usr/local/bundle:cached
      - /date_suggester/vendor
      - /date_suggester/tmp
      - /date_suggester/log
      - /date_suggester/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db:
  bundle:
