version: '3'
services:
  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'root'
      TZ: Asia/Tokyo
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/date_suggester
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db: