default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RDS_HOSTNAME") { "db" } %>
  username: <%= ENV.fetch("RDS_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("RDS_PASSWORD") { "root" } %>
  port: <%= ENV.fetch("RDS_PORT") { "5432" } %>

development:
  <<: *default
  database: date-suggester-rails_development

test:
  <<: *default
  database: date-suggester-rails_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
