default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "root" } %>

development:
  <<: *default
  database: <%= ENV['DEV_DB_NAME'] { "date-suggester-rails_development" } %>
  host: db

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] { "date-suggester-rails_test" } %>
  host: db

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
