default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: db

development:
  <<: *default
  database: date-suggester-rails_development

test:
  <<: *default
  database: date-suggester-rails_test

production:
  <<: *default
  database: date-suggester-rails_production
  username: date-suggester-rails
  password: <%= ENV['DATE-SUGGESTER-RAILS_DATABASE_PASSWORD'] %>
